import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { ensureProjectForUser, userHasProjectAccess } from "@/lib/projects";
import { buildBugWhere } from "@/lib/bug-filters";
import {
  bugSeverityLabel,
  bugPriorityLabel,
  bugStatusLabel,
  detectionSourceLabel,
  detectionPhaseLabel,
  rootCauseLabel,
} from "@/lib/bug-enums";

const CSV_COLUMNS = [
  "Bug ID",
  "External Issue ID",
  "Title",
  "Module",
  "Severity",
  "Priority",
  "Status",
  "Detection Source",
  "Detection Phase",
  "Leaked",
  "Root Cause",
  "Reopen Count",
  "Assigned Developer",
  "Responsible QA",
  "Reporter",
  "Sprint",
  "Release",
  "Fix Version",
  "Created At",
  "Closed At",
] as const;

function escapeCsv(value: string) {
  if (/[",\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function toRow(values: (string | number | null)[]) {
  return values.map((v) => escapeCsv(v === null || v === undefined ? "" : String(v))).join(",");
}

export async function GET(request: Request) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(request.url);
  const requestedProjectId = searchParams.get("projectId");

  const project = requestedProjectId
    ? { id: requestedProjectId }
    : await ensureProjectForUser(session.user.id);

  if (!project) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!(await userHasProjectAccess(session.user.id, project.id))) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const projectRecord = await db.project.findUnique({
    where: { id: project.id },
    select: { name: true },
  });

  const where = buildBugWhere(searchParams, project.id);

  const bugs = await db.bug.findMany({
    where,
    include: {
      module: true,
      assignedDeveloper: { select: { name: true, email: true } },
      responsibleQa: { select: { name: true, email: true } },
      reporter: { select: { name: true, email: true } },
    },
    orderBy: { createdAt: "desc" },
    take: 10_000,
  });

  const lines: string[] = [];
  lines.push(`# Project: ${projectRecord?.name ?? project.id}`);
  lines.push(`# Export date: ${new Date().toISOString()}`);
  lines.push(`# Applied filters: ${searchParams.toString() || "none"}`);
  lines.push(`# Generated by: ${session.user.email ?? session.user.id}`);
  lines.push(toRow([...CSV_COLUMNS]));

  for (const bug of bugs) {
    lines.push(
      toRow([
        bug.displayId,
        bug.externalIssueId,
        bug.title,
        bug.module?.name ?? null,
        bugSeverityLabel(bug.severity),
        bugPriorityLabel(bug.priority),
        bugStatusLabel(bug.status),
        detectionSourceLabel(bug.detectionSource),
        detectionPhaseLabel(bug.detectionPhase),
        bug.isLeaked ? "Yes" : "No",
        bug.rootCause ? rootCauseLabel(bug.rootCause) : null,
        bug.reopenCount,
        bug.assignedDeveloper?.name ?? bug.assignedDeveloper?.email ?? null,
        bug.responsibleQa?.name ?? bug.responsibleQa?.email ?? null,
        bug.reporter?.name ?? bug.reporter?.email ?? null,
        bug.sprint,
        bug.release,
        bug.fixVersion,
        bug.createdAt.toISOString(),
        bug.closedDate ? bug.closedDate.toISOString() : null,
      ])
    );
  }

  const csv = lines.join("\n");

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="bug-register-${project.id}.csv"`,
    },
  });
}
