name: Deploy to Coolify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: curlimages/curl:latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          echo "Triggering Coolify deploy..."
          echo "$COOLIFY_WEBHOOK"
          echo "$COOLIFY_DEPLOY_TOKEN"
