name: Deploy to Coolify
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          echo "Triggering Coolify deploy..."
          echo "$COOLIFY_WEBHOOK"
          echo "$COOLIFY_DEPLOY_TOKEN"
